### ISSUE TITLE
Panic when setting device settings for edge on v4.0.0 API

### ISSUE THREAD

**Issue by MrLemur** [adeleporte/terraform-provider-velocloud#1]
Hi,

Trying to follow the example to set up a virtual edge in AWS, but unable to get it to work. Here is the error after apply is run:

```
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: panic: interface conversion: interface {} is nil, not []interface {}
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: 
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: goroutine 97 [running]:
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: main.resourceDeviceSettingsCreate(0xd3e1a0, 0xc000748720, 0xc000768780, 0xb38c20, 0xc000320240, 0xc00074ce60, 0x6c4ada, 0xc0004da820)
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/adeleporte/terraform-provider-velocloud/resource_device_settings.go:123 +0xe99
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000308dc0, 0xd3e120, 0xc00074a1c0, 0xc000768780, 0xb38c20, 0xc000320240, 0x0, 0x0, 0x0)
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/helper/schema/resource.go:276 +0x1ec
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000308dc0, 0xd3e120, 0xc00074a1c0, 0xc000762230, 0xc0004da820, 0xb38c20, 0xc000320240, 0x0, 0x0, 0x0, ...)
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/helper/schema/resource.go:387 +0x681
2020-11-30T11:18:10.631Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000c1c0, 0xd3e120, 0xc00074a1c0, 0xc000762000, 0xc00000c1c0, 0xc00000c1d0, 0xc56b60)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/internal/helper/plugin/grpc_provider.go:952 +0x8b2
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler.func1(0xd3e120, 0xc00074a1c0, 0xbec000, 0xc000762000, 0xc00074a1c0, 0xb6f0c0, 0xc000748101, 0xc0004da5c0)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/internal/tfplugin5/tfplugin5.pb.go:3312 +0x86
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0xd3e1e0, 0xc0007501b0, 0xbec000, 0xc000762000, 0xc0004da5a0, 0xc0004da5c0, 0xc0005e4ba0, 0x4906d8, 0xbc4540, 0xc0007501b0)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/plugin/serve.go:76 +0x87
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xbf9ea0, 0xc00000c1c0, 0xd3e1e0, 0xc0007501b0, 0xc0007481e0, 0xc00051c440, 0xd3e1e0, 0xc0007501b0, 0xc000760120, 0x103)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/internal/tfplugin5/tfplugin5.pb.go:3314 +0x14b
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032c380, 0xd466e0, 0xc00008ad80, 0xc00075c000, 0xc0000a4720, 0x123bd40, 0x0, 0x0, 0x0)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: google.golang.org/grpc.(*Server).handleStream(0xc00032c380, 0xd466e0, 0xc00008ad80, 0xc00075c000, 0x0)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000034210, 0xc00032c380, 0xd466e0, 0xc00008ad80, 0xc00075c000)
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-30T11:18:10.632Z [DEBUG] plugin.terraform-provider-velocloud_v0.2.9:    google.golang.org/grpc@v1.30.0/server.go:832 +0x204
2020-11-30T11:18:10.635Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/11/30 11:18:10 [DEBUG] velocloud_device_settings.dv1: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
```

Looking at the module, it is expecting a `routedInterfaces` array from the `data` node in the Velocloud API response. I've run this API call through Postman, and nothing is returned for `modules`>`deviceSettings`>`data`.

**Comment by adeleporte** [comment]
Hi,
could you share your velocloud_device_settings TF resource definition (especially the profile parameter)?

My guess is that you're using something like **data.velocloud_profile.newtf.id**, instead of **velocloud_edge.edge1.edgeprofileid**
(like in [https://registry.terraform.io/providers/adeleporte/velocloud/latest/docs/resources/device_settings](https://registry.terraform.io/providers/adeleporte/velocloud/latest/docs/resources/device_settings))

Actually Edges have a device_settings module by default, but Profiles don't have such module by default. So, **today, the TF provider supports Device Settings configuration only at Edge Level, not at Profile Level**.

Hope this helps.
Antoine

**Comment by MrLemur** [comment]
Thanks for the information, that was indeed the problem! I look forward to the profile support if it comes.
